#ifndef CPUPROPERTIES_H_INCLUDED
#define CPUPROPERTIES_H_INCLUDED

#define WRONG_SIGNATURE "WRONGSIGNATURE"
const int  WRONG_VERSION        = -1;
const char GENUINE_SIGNATURE[]  = "EK";
const int  GENUINE_VERSION      = 7;

const int RAM_SIZE   = 10000;
const int LABELS_MAX = 10000;

#endif // CPUPROPERTIES_H_INCLUDED
