#ifndef CPUPROPERTIES_H_INCLUDED
#define CPUPROPERTIES_H_INCLUDED

#define WRONG_SIGNATURE "WRONGSIGNATURE"
const int  WRONG_VERSION        = -1;
const char GENUINE_SIGNATURE[]  = "EK";
const int  GENUINE_VERSION      = 2;

const int RAM_SIZE   = 1024;
const int LABELS_MAX = 1000;

#endif // CPUPROPERTIES_H_INCLUDED
