#ifndef ERRORS_H_INCLUDED
#define ERRORS_H_INCLUDED

enum ERR_CODE{
    FATAL_ERROR = -1,
    SUCCESS     = 0,
    BAD_ALLOC,
    NOT_ENOUGH_ELEMENTS,
    OVERFLOWN,

    FIRST_EDGE_BROKEN,
    SCOND_EDGE_BROKEN,
    STACK_NULL,
    HASH_WRONG,

    FILE_NOT_FOUND,
    FILE_POS_ERROR,
    READ_ERROR,
    FILE_ERROR,

    BAD_SIGNATURE,
    BAD_VERSION
};

#endif // ERRORS_H_INCLUDED
