#ifndef ERRORS_H_INCLUDED
#define ERRORS_H_INCLUDED

enum ERR_CODE{
    SUCCESS = 0,
    BAD_ALLOC,
    NOT_ENOUGH_ELEMENTS,
    OVERFLOWN,

    FIRST_EDGE_BROKEN,
    SCOND_EDGE_BROKEN,
    HASH_WRONG
};

#endif // ERRORS_H_INCLUDED
